package com.github.jairrab.currencyutility.lib.helpers

import com.github.jairrab.currencyutility.model.CurrencyData

object CryptoHelper {
    fun isCryptoCurrency(currency: String) =
        cryptoList.map { it.currency }.contains(currency)

    fun getApiCode(currency: String) =
        cryptoList.firstOrNull { it.currency == currency }?.apiCode ?: "xxx"

    val cryptoList by lazy {
        listOf(
            CurrencyData("ACT", "Achain (Cryptocurrency)", "achain"),
            CurrencyData("ADA", "Cardano (Cryptocurrency)", "cardano"),
            CurrencyData("ADX", "AdEx (Cryptocurrency)", "adx-net"),
            CurrencyData("AE", "Aeternity (Cryptocurrency)", "aeternity"),
            CurrencyData("ARDR", "Ardor (Cryptocurrency)", "ardor"),
            CurrencyData("ARK", "Ark (Cryptocurrency)", "ark"),
            CurrencyData("BAT", "Basic Attenti... (Cryptocurrency)", "basic-attention-token"),
            CurrencyData("BCC", "BitConnect (Cryptocurrency)", "bitconnect"),
            CurrencyData("BCH", "Bitcoin Cash (Cryptocurrency)", "bitcoin-cash"),
            CurrencyData("BCN", "Bytecoin (Cryptocurrency)", "bytecoin-bcn"),
            CurrencyData("BLOCK", "Blocknet (Cryptocurrency)", "blocknet"),
            CurrencyData("BNB", "Binance Coin (Cryptocurrency)", "binance-coin"),
            CurrencyData("BNT", "Bancor (Cryptocurrency)", "bancor"),
            CurrencyData("BTC", "Bitcoin (Cryptocurrency)", "bitcoin"),
            CurrencyData("BTCD", "BitcoinDark (Cryptocurrency)", "bitcoindark"),
            CurrencyData("BTG", "Bitcoin Gold (Cryptocurrency)", "bitcoin-gold"),
            CurrencyData("BTM", "Bytom (Cryptocurrency)", "bytom"),
            CurrencyData("BTS", "BitShares (Cryptocurrency)", "bitshares"),
            CurrencyData("CNX", "Cryptonex (Cryptocurrency)", "cryptonex"),
            CurrencyData("CVC", "Civic (Cryptocurrency)", "civic"),
            CurrencyData("DAI", "DAI (Cryptocurrency)", "dai"),
            CurrencyData("DCR", "Decred (Cryptocurrency)", "decred"),
            CurrencyData("DGB", "DigiByte (Cryptocurrency)", "digibyte"),
            CurrencyData("DGD", "DigixDAO (Cryptocurrency)", "digixdao"),
            CurrencyData("DOGE", "Dogecoin (Cryptocurrency)", "dogecoin"),
            CurrencyData("DSH", "Dash (Cryptocurrency)", "dash"),
            CurrencyData("EDG", "Edgeless (Cryptocurrency)", "edgeless"),
            CurrencyData("EMC2", "Einsteinium (Cryptocurrency)", "einsteinium"),
            CurrencyData("EOS", "EOS (Cryptocurrency)", "eos"),
            CurrencyData("ETC", "Ethereum Classic (Cryptocurrency)", "ethereum-classic"),
            CurrencyData("ETH", "Ethereum (Cryptocurrency)", "ethereum"),
            CurrencyData("ETHOS", "Ethos (Cryptocurrency)", "ethos"),
            CurrencyData("ETP", "Metaverse ETP (Cryptocurrency)", "metaverse"),
            CurrencyData("FCT", "Factom (Cryptocurrency)", "factom"),
            CurrencyData("FUN", "FunFair (Cryptocurrency)", "funfair"),
            CurrencyData("GAME", "GameCredits (Cryptocurrency)", "gamecredits"),
            CurrencyData("GAS", "Gas (Cryptocurrency)", "gas"),
            CurrencyData("GBYTE", "Byteball Bytes (Cryptocurrency)", "byteball"),
            CurrencyData("GNO", "Gnosis (Cryptocurrency)", "gnosis-gno"),
            CurrencyData("GNT", "Golem (Cryptocurrency)", "bitshares"),
            CurrencyData("GRS", "Groestlcoin (Cryptocurrency)", "groestlcoin"),
            CurrencyData("GXS", "GXShares (Cryptocurrency)", "gxshares"),
            CurrencyData("HSR", "Hshare (Cryptocurrency)", "hshare"),
            CurrencyData("ICN", "Iconomi (Cryptocurrency)", "iconomi"),
            CurrencyData("ICX", "Icon (Cryptocurrency)", "icon"),
            CurrencyData("KMD", "Komodo (Cryptocurrency)", "komodo"),
            CurrencyData("KNC", "Kyber Network (Cryptocurrency)", "kyber-network"),
            CurrencyData("LINK", "ChainLink (Cryptocurrency)", "chainlink"),
            CurrencyData("LRC", "Loopring (Cryptocurrency)", "loopring"),
            CurrencyData("LSK", "Lisk (Cryptocurrency)", "lisk"),
            CurrencyData("LTC", "Litecoin (Cryptocurrency)", "litecoin"),
            CurrencyData("MAID", "MaidSafeCoin (Cryptocurrency)", "maidsafecoin"),
            CurrencyData("MCO", "Monaco (Cryptocurrency)", "monaco"),
            CurrencyData("MIOTA", "IOTA (Cryptocurrency)", "iota"),
            CurrencyData("MNX", "MinexCoin (Cryptocurrency)", "minexcoin"),
            CurrencyData("MONA", "MonaCoin (Cryptocurrency)", "monacoin"),
            CurrencyData("MTL", "Metal (Cryptocurrency)", "metal"),
            CurrencyData("NAV", "NAV Coin (Cryptocurrency)", "nav-coin"),
            CurrencyData("NEO", "NEO (Cryptocurrency)", "neo"),
            CurrencyData("NXS", "Nexus (Cryptocurrency)", "nexus"),
            CurrencyData("NXT", "Nxt (Cryptocurrency)", "nxt"),
            CurrencyData("OMG", "OmiseGO (Cryptocurrency)", "omisego"),
            CurrencyData("PAY", "TenX (Cryptocurrency)", "tenx"),
            CurrencyData("PIVX", "PIVX (Cryptocurrency)", "pivx"),
            CurrencyData("POT", "PotCoin (Cryptocurrency)", "potcoin"),
            CurrencyData("POWR", "Power Ledger (Cryptocurrency)", "xpower-ledger"),
            CurrencyData("PPT", "Populous (Cryptocurrency)", "populous"),
            CurrencyData("PURA", "Pura (Cryptocurrency)", "pura"),
            CurrencyData("QASH", "QASH (Cryptocurrency)", "qash"),
            CurrencyData("QTUM", "Qtum (Cryptocurrency)", "qtum"),
            CurrencyData("RDN", "Raiden Networ... (Cryptocurrency)", "raiden-network-token"),
            CurrencyData("REP", "Augur (Cryptocurrency)", "augur"),
            CurrencyData("SALT", "SALT (Cryptocurrency)", "salt"),
            CurrencyData("SAN", "Santiment Net... (Cryptocurrency)", "santiment"),
            CurrencyData("SC", "Siacoin (Cryptocurrency)", "siacoin"),
            CurrencyData("SKY", "Skycoin (Cryptocurrency)", "skycoin"),
            CurrencyData("SNGLS", "SingularDTV (Cryptocurrency)", "singulardtv"),
            CurrencyData("SNT", "Status (Cryptocurrency)", "status"),
            CurrencyData("STEEM", "Steem (Cryptocurrency)", "steem"),
            CurrencyData("STORJ", "Storj (Cryptocurrency)", "storj"),
            CurrencyData("STRAT", "Stratis (Cryptocurrency)", "stratis"),
            CurrencyData("SUB", "Substratum (Cryptocurrency)", "substratum"),
            CurrencyData("SYS", "Syscoin (Cryptocurrency)", "syscoin"),
            CurrencyData("TRX", "TRON (Cryptocurrency)", "tron"),
            CurrencyData("UBQ", "Ubiq (Cryptocurrency)", "ubiq"),
            CurrencyData("USDT", "Tether (Cryptocurrency)", "tether"),
            CurrencyData("VEN", "VeChain (Cryptocurrency)", "vechain"),
            CurrencyData("VERI", "Veritaseum (Cryptocurrency)", "veritaseum"),
            CurrencyData("VIU", "Viuly (Cryptocurrency)", "viuly"),
            CurrencyData("VTC", "Vertcoin (Cryptocurrency)", "vertcoin"),
            CurrencyData("WAVES", "Waves (Cryptocurrency)", "waves"),
            CurrencyData("WTC", "Walton (Cryptocurrency)", "walton"),
            CurrencyData("XCP", "Counterparty (Cryptocurrency)", "counterparty"),
            CurrencyData("XEM", "NEM (Cryptocurrency)", "nem"),
            CurrencyData("XLM", "Stellar Lumens (Cryptocurrency)", "stellar"),
            CurrencyData("XMR", "Monero (Cryptocurrency)", "monero"),
            CurrencyData("XRP", "Ripple (Cryptocurrency)", "ripple"),
            CurrencyData("XUC", "Exchange Union (Cryptocurrency)", "exchange-union"),
            CurrencyData("XVG", "Verge (Cryptocurrency)", "verge"),
            CurrencyData("XZC", "ZCoin (Cryptocurrency)", "zcoin"),
            CurrencyData("YOYOW", "YOYOW (Cryptocurrency)", "yoyow"),
            CurrencyData("ZEC", "Zcash (Cryptocurrency)", "zcash"),
            CurrencyData("ZEN", "ZenCash (Cryptocurrency)", "zencash"),
            CurrencyData("ZRX", "0x (Cryptocurrency)", "0x"),
        )
    }
}
